# Static configuration

api:
  dashboard: true
  insecure: true

# log:
#   level: DEBUG

experimental:
  localPlugins:
    example:
      moduleName: github.com/fluxninja/aperturetraefikplugin

entryPoints:
  http:
    address: ":8000"
    forwardedHeaders:
      insecure: true


providers:
  file:
    filename: dyanmic-rule-config.yaml
